name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.release-please-manifest.json'
      - 'release-please-config.json'
      - 'docs/**'
      - 'LICENSE'

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go:
    uses: st0o0/github-workflows/.github/workflows/go-ci.yml@main
    with:
      docker-image-name: ran

  commits:
    uses: st0o0/github-workflows/.github/workflows/commitlint.yml@main
