name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    uses: st0o0/github-workflows/.github/workflows/go-release.yml@main
    with:
      image-name: ghcr.io/st0o0/ran
      image-description: "Go honeypot container -- traps and logs unauthorized access attempts"
    permissions:
      contents: write
      pull-requests: write
      packages: write
      id-token: write
